version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/examples/using-gatsby-source-local-git"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
